import { escapeHtml } from './dom.js';
import { speakerLabel } from './transcripts.js';

export const browserDownloadFile = (filename, content, mimeType = 'text/plain;charset=utf-8') => {
    const body = /application\/(vnd\.ms-excel|msword)/i.test(mimeType)
        ? `\ufeff${content}`
        : content;
    const blob = new Blob([body], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    window.setTimeout(() => {
        link.remove();
        URL.revokeObjectURL(url);
    }, 1000);

    if (typeof window.showNotification === 'function') {
        window.showNotification(`Export download started: ${filename}`, 'success');
    }
};

export const saveTranscriptExport = async ({
    filename,
    content,
    mimeType = 'text/plain;charset=utf-8',
    extension = 'txt',
    filterName = 'Text files',
}) => {
    const invoke = window.__TAURI__?.core?.invoke;

    if (typeof invoke !== 'function') {
        browserDownloadFile(filename, content, mimeType);
        return;
    }

    try {
        const path = await invoke('save_text_export_with_dialog', {
            content,
            filename,
            defaultExtension: extension,
            filterName,
            filterExtensions: [extension],
        });

        if (path && typeof window.showNotification === 'function') {
            window.showNotification(`Export saved to ${path}`, 'success');
        }
    } catch (error) {
        if (extension !== 'txt') {
            browserDownloadFile(filename, content, mimeType);
            return;
        }

        try {
            const path = await invoke('save_text_export_with_dialog', { content });

            if (path && typeof window.showNotification === 'function') {
                window.showNotification(`Export saved to ${path}`, 'success');
            }
        } catch (fallbackError) {
            if (typeof window.showNotification === 'function') {
                const message = String(fallbackError || error || '').trim();
                window.showNotification(message || 'Could not save the export. Please try again.', 'error');
            }
        }
    }
};

export const saveTextExport = (filename, content) => saveTranscriptExport({
    filename,
    content,
    mimeType: 'text/plain;charset=utf-8',
    extension: 'txt',
    filterName: 'Text files',
});

export const exportRowsToText = (rows) => rows
    .map((row) => [row.rangeLabel, row.transcriptText].filter(Boolean).join('\n'))
    .join('\n\n');

const exportDocumentTitle = (title, variantLabel) => `${title} - ${variantLabel} Transcript`;

const exportRowsToSpreadsheetHtml = ({ title, variantLabel, rows }) => `<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Calibri, Arial, sans-serif; color: #0f172a; }
        h1 { color: #0891b2; font-size: 22px; margin: 0 0 4px; }
        .meta { color: #64748b; font-size: 12px; margin: 0 0 14px; }
        table { border-collapse: collapse; width: 100%; }
        th { background: #0f172a; color: #ffffff; font-weight: 700; padding: 9px; text-align: left; border: 1px solid #1e293b; }
        td { padding: 8px; vertical-align: top; border: 1px solid #cbd5e1; }
        tr:nth-child(even) td { background: #f8fafc; }
        .range { color: #0891b2; font-weight: 700; white-space: nowrap; }
        .speaker { color: #0f766e; font-weight: 700; }
        .transcript { white-space: pre-wrap; line-height: 1.35; }
    </style>
</head>
<body>
    <h1>${escapeHtml(exportDocumentTitle(title, variantLabel))}</h1>
    <p class="meta">Generated by ASTRA AITranscriber</p>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Time Range</th>
                <th>Speakers</th>
                <th>Transcript</th>
            </tr>
        </thead>
        <tbody>
            ${rows.map((row, index) => `
                <tr>
                    <td>${index + 1}</td>
                    <td class="range">${escapeHtml(row.rangeLabel)}</td>
                    <td class="speaker">${escapeHtml(row.speakerLabels.join(', ') || 'Transcript')}</td>
                    <td class="transcript">${escapeHtml(row.transcriptText)}</td>
                </tr>
            `).join('')}
        </tbody>
    </table>
</body>
</html>`;

const exportRowsToWordHtml = ({ title, variantLabel, rows }) => `<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Calibri, Arial, sans-serif; color: #111827; line-height: 1.5; }
        .page { max-width: 760px; margin: 0 auto; }
        h1 { margin: 0 0 4px; color: #0f172a; font-size: 26px; }
        .subtitle { margin: 0 0 20px; color: #64748b; font-size: 12px; text-transform: uppercase; letter-spacing: 1.8px; }
        .section { border-top: 2px solid #bae6fd; padding: 14px 0 10px; }
        .range { display: inline-block; margin-bottom: 8px; padding: 4px 8px; border-radius: 999px; background: #ecfeff; color: #0e7490; font-weight: 700; }
        p { margin: 0 0 8px; }
        .speaker { color: #0f766e; font-weight: 700; }
    </style>
</head>
<body>
    <div class="page">
        <h1>${escapeHtml(exportDocumentTitle(title, variantLabel))}</h1>
        <p class="subtitle">Generated by ASTRA AITranscriber</p>
        ${rows.map((row) => `
            <div class="section">
                <div class="range">${escapeHtml(row.rangeLabel || 'Transcript')}</div>
                ${row.turns.length
                    ? row.turns.map((turn) => `<p><span class="speaker">${escapeHtml(speakerLabel(turn.speakerId))}:</span> ${escapeHtml(turn.text)}</p>`).join('')
                    : `<p>${escapeHtml(row.transcriptText)}</p>`}
            </div>
        `).join('')}
    </div>
</body>
</html>`;

export const exportTranscriptRows = ({ rows, format, filenameBase, title, variantLabel }) => {
    const normalizedFormat = String(format || 'txt').toLowerCase();

    if (normalizedFormat === 'excel') {
        return saveTranscriptExport({
            filename: `${filenameBase}.xls`,
            content: exportRowsToSpreadsheetHtml({ title, variantLabel, rows }),
            mimeType: 'application/vnd.ms-excel;charset=utf-8',
            extension: 'xls',
            filterName: 'Excel files',
        });
    }

    if (normalizedFormat === 'word') {
        return saveTranscriptExport({
            filename: `${filenameBase}.doc`,
            content: exportRowsToWordHtml({ title, variantLabel, rows }),
            mimeType: 'application/msword;charset=utf-8',
            extension: 'doc',
            filterName: 'Word documents',
        });
    }

    return saveTextExport(`${filenameBase}.txt`, exportRowsToText(rows));
};
