[PHP]
extension_dir = "ext"
memory_limit = -1
max_execution_time = 0
max_input_time = 0
upload_max_filesize = 1024G
post_max_size = 0
display_errors = Off
log_errors = On
variables_order = "GPCS"
date.timezone = "Asia/Shanghai"

[curl]
curl.cainfo = "php/extras/ssl/cacert.pem"

[openssl]
openssl.cafile = "php/extras/ssl/cacert.pem"

extension=curl
extension=bz2
extension=fileinfo
extension=mbstring
extension=openssl
extension=pdo_sqlite
extension=sqlite3
extension=zip

[opcache]
opcache.enable=0
opcache.enable_cli=0
