export const createLiveWorkflowState = ({ categoryName = '' } = {}) => ({
    isRecording: false,
    stream: null,
    recorder: null,
    progressTimer: null,
    autoStopTimer: null,
    sessionStartedAt: 0,
    segmentStartedAt: 0,
    segmentIndex: 0,
    queuedItems: [],
    storedItems: [],
    activeParts: [],
    activeAudio: null,
    activeAudioId: null,
    activePlaybackKind: null,
    uploadInFlight: false,
    activeUploadXhr: null,
    activeUploadItemId: null,
    activeWhisperProgressId: '',
    activeLivePhaseProgress: null,
    activeLivePhaseTimer: null,
    cancelUploadByUser: false,
    uploadPaused: false,
    liveCleanerStatus: 'Waiting',
    activeCategoryName: String(categoryName || '').trim(),
    liveShowingVadLogs: false,
    activeSpeakerSessionId: '',
});
